[package]
name = "gamma-correction-demo"
version = "0.1.0"
license = "MIT/Apache-2.0"
authors = ["Henning Ottesen <henning@live.no>"]

[dependencies.sdl2]
features = ["use-pkgconfig"]
version = "0.31"
